version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        env: dev
    ports:
      - '8080:8080'
    depends_on:
      - db
    env_file:
      - env-postgres.env
      - env-backend.env
  redis:
    image: "redis:alpine"
  db:
    image: mdillon/postgis:11
#    env_file:
#      - env-postgres.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata